# -*- coding: utf-8 -*-
"""lab08_2502190039.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pLaD-aS72rk4doTEVKj5L7o2KkFSUn9u
"""

# JOB A — The Alarm Book

The following six Python exceptions were intentionally triggered to observe their error messages.

```python
# 1. ValueError
int("abc")

# 2. ZeroDivisionError
10 / 0

# 3. IndexError
numbers = [10, 20, 30]
numbers[5]

# 4. KeyError
data = {"name": "Ayushi"}
data["age"]

# 5. TypeError
"10" + 5

# 6. AttributeError
x = 10
x.append(5)
```

### Observed Errors

| No. | Error               | Last line of message                            |
| --- | ------------------- | ----------------------------------------------- |
| 1   | `ValueError`        | `invalid literal for int() with base 10: 'abc'` |
| 2   | `ZeroDivisionError` | `division by zero`                              |
| 3   | `IndexError`        | `list index out of range`                       |
| 4   | `KeyError`          | `'age'`                                         |
| 5   | `TypeError`         | `can only concatenate str (not "int") to str`   |
| 6   | `AttributeError`    | `'int' object has no attribute 'append'`        |

```

**Note:** Colab mein code ko practically run karte time har statement separately run karna, because first error ke baad same cell ki execution stop ho jayegi.
```

# 1. ValueError
int("abc")

# 2. ZeroDivisionError
10 / 0

# 3. IndexError
numbers = [10, 20, 30]
numbers[5]

# 4. KeyError
data = {"name": "Ayushi"}
data["age"]

# 5. TypeError
"10" + 5

# 6. AttributeError
x = 10
x.append(5)

# 6. AttributeError
x = 10
x.append(5)

#------------JOB_B------------------------


def parse_line(line):
    parts = line.strip().split(",")

    if len(parts) != 2:
        raise ValueError("Expected code, diameter")

    code = parts[0].strip()
    family = code.split("-")[1]
    dia = float(parts[1].strip())

    return code, family, dia


dirty = [
    "MS-FLG-2026-0041, 24.98",
    "AL-BRK-2026-0007, abc",
    "MS-FLG-2026-0043",
    "SS-GER-2026-0021, 25.04",
    "",
    "ms-shf-2026-0101, 24.88",
]

good, skipped = [], []

for n, line in enumerate(dirty, start=1):
    try:
        code, family, dia = parse_line(line)
        good.append((code, family, dia))

    except ValueError as e:
        skipped.append((n, "ValueError", str(e)))

    except IndexError as e:
        skipped.append((n, "IndexError", str(e)))


print(len(good), "accepted,", len(skipped), "skipped")

# Report
mean = sum(x[2] for x in good) / len(good)
print("Mean:", round(mean, 3))

print("Count:", len(good))

families = {}
for code, family, dia in good:
    families[family] = families.get(family, 0) + 1

print("Families:", families)

# Reject Note
print("\nREJECT NOTE")

for n, error, message in skipped:
    print("Line", n, "|", error, "|", dirty[n-1])

#-----------JOB_C--------------


class Shaft:
    def __init__(self, code, dia):
        if dia <= 0:
            raise ValueError("Diameter must be positive")

        self.code = code
        self.dia = dia


# Add impossible value
good.append(("TEST-NEG-0001", "NEG", -5))

fleet, rejects = [], []

for code, family, dia in good:
    try:
        fleet.append(Shaft(code, dia))

    except ValueError as e:
        rejects.append((code, str(e)))


print("Fleet:", len(fleet))
print("Rejects:", rejects)